apiVersion: terraform.brainstation.au/v1
kind: Backend
metadata:
  labels:
    app.kubernetes.io/name: k8s-operator-terraform
    app.kubernetes.io/managed-by: kustomize
  name: backend-sample
spec:
  # TODO(user): Add fields here
